name: Restore & Install Rush
description: Restore Rush bootstrap and dependency caches, then run rush install
runs:
  using: composite
  steps:
    - name: Restore Rush bootstrap from cache
      uses: actions/cache/restore@v5
      id: rush_bootstrap_cache
      with:
        path: common/temp/install-run
        key: rush-bootstrap-${{ hashFiles('rush.json') }}

    - name: Restore Rush deps from cache
      uses: actions/cache/restore@v5
      id: rush_cache
      with:
        path: |
          common/temp/node_modules
          common/temp/pnpm-store
        key: rush-deps-${{ hashFiles('rush.json', 'common/config/rush/pnpm-lock.yaml') }}

    - name: Rush bootstrap cache status
      if: steps.rush_bootstrap_cache.outputs.cache-hit != 'true'
      run: |
        echo "Rush bootstrap cache miss"
      shell: bash

    - name: Rush cache status
      if: steps.rush_cache.outputs.cache-hit != 'true'
      run: |
        echo Rush deps cache miss
      shell: bash

    - name: Install Rush deps
      run: |
        node common/scripts/install-run-rush.js install --max-install-attempts 1
      shell: bash

    - name: Save Rush bootstrap in cache
      uses: actions/cache/save@v5
      if: steps.rush_bootstrap_cache.outputs.cache-hit != 'true'
      with:
        path: common/temp/install-run
        key: rush-bootstrap-${{ hashFiles('rush.json') }}

    - name: Save Rush deps in cache
      uses: actions/cache/save@v5
      if: steps.rush_cache.outputs.cache-hit != 'true'
      with:
        path: |
          common/temp/node_modules
          common/temp/pnpm-store
        key: rush-deps-${{ hashFiles('rush.json', 'common/config/rush/pnpm-lock.yaml') }}
