services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      # change these to something secure (for dev you can keep simple)
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8888:80
    volumes:
      # Persist pgAdmin settings & connections
      - pgadmin_data:/var/lib/pgadmin

  server:
    build: ./apps/server
    restart: on-failure
    environment:
      # trunk-ignore(checkov/CKV_SECRET_4)
      DATABASE_URL: postgres://chatuser:chatpass@postgres:5432/chatdb
    ports:
      - 4000:80
    depends_on:
      - postgres

  client:
    build: ./apps/client
    restart: on-failure
    ports:
      - 3000:80
    environment:
      REACT_APP_GRAPHQL_URL: http://localhost:4000/graphql

volumes:
  pgadmin_data:
  postgres_data:
