services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.debian-base
    # userns_mode: keep-id
    user: root
    volumes:
      - ..:/workspace:rw,Z
      # - typescript_monorepo_nestjs_relay_trunk-home:/home/vscode:rw,Z
    environment:
      # trunk-ignore(trufflehog/Postgres)
      # trunk-ignore(checkov/CKV_SECRET_4)
      DATABASE_URL: postgres://chatuser:chatpass@postgres:5432/chatdb
      REDIS_URL: redis://redis:6379
      DOCKER_HOST: unix:///run/host-user-runtime/podman/podman.sock
    depends_on:
      - postgres
      - redis
    command: sleep infinity
    mem_limit: 20g
    memswap_limit: 22g
    oom_kill_disable: false
    oom_score_adj: 500
