name: deploy-webapp

on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/ci-release.yaml
    with:
      force_targets_json: '["webapp"]'
    secrets: inherit
