name: force-deploy-webapp

on:
  workflow_dispatch:

permissions: {}

jobs:
  force-webapp-deploy:
    permissions:
      contents: write
      id-token: write
      packages: write
    uses: ./.github/workflows/main-workflow.yaml
    with:
      force_targets_json: '["webapp"]'
    secrets: inherit
