# yaml-language-server: $schema=https://bootstraplaboratory.github.io/rush-delivery/schemas/deploy-services-mesh.schema.json

services:
  server:
    deploy_after: []

  webapp:
    deploy_after:
      - server
